# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key

Layout/SpaceAroundOperators:
  Enabled: true
